title: CF212 - Data structures and Algorithms
author: thangdn
email: thangdn.tlu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A Site for Mathematics and Informatics students at Thang Long University.

twitter_username: cstlu
github_username:  cstlu

sass:
    style: compressed
